#!/usr/bin/env python3
"""
prompt-build.py — 从 base + compliance-block + preflight + delta 生成各平台最终 prompt
Usage: python3 .prompt-src/prompt-build.py [--apply] [--apply-block] [--verify] [--diff]
  默认：生成到 .prompt-src/_build/ 并输出 diff 报告
  --apply：覆盖自动平台目标文件（需人工确认）
  --apply-block：替换手动平台 V9-COMPLIANCE-BLOCK 标记间的共享内容
  --verify：检查所有目标（自动+手动+deprecated）的一致性，任何 drift 非零退出
  --diff：只输出 diff，不生成文件

V9 Phase 0.6 (2026-06-11):
  - 自动平台也从 v9-compliance-block.md 生成合规段（单一真理源）
  - prompt-base.md 使用 <!-- V9-COMPLIANCE-INJECT --> 占位
  - preflight-auto-template.md 提供自动平台的 pre-flight 模板
  - --verify 全文块比较，任何 drift 非零退出
  - content_hash 修正：只在有 header 时剥离
  - 源文件支持 frontmatter；生成时剥离 metadata，只保留正文
  - DEPRECATED 追踪（assistant → claudian）
"""

import os
import sys
import re
import hashlib
import difflib
from pathlib import Path

VAULT = Path(os.path.expanduser("~/Desktop/obsidianVault"))
SRC = VAULT / ".prompt-src"
BUILD = SRC / "_build"
AGENTS_DIR = SRC / "agents"

# 源文件
COMPLIANCE_BLOCK_SRC = SRC / "v9-compliance-block.md"
PREFLIGHT_AUTO_SRC = SRC / "preflight-auto-template.md"

# 平台目标映射
TARGETS = {
    "claudian": {
        "platform": "claude-code",
        "target": VAULT / ".claude" / "agents" / "claudian.md",
        "build": BUILD / "claude-claudian.md",
    },
    "qingmeisu": {
        "platform": "claude-code",
        "target": VAULT / ".claude" / "agents" / "qingmeisu.md",
        "build": BUILD / "claude-qingmeisu.md",
    },
    "hongmeisu": {
        "platform": "codex",
        "target": VAULT / ".codex" / "instructions.md",
        "build": BUILD / "codex-instructions.md",
    },
    "toubao": {
        "platform": "hermes",
        "target": Path(os.path.expanduser("~/.hermes/SOUL.md")),
        "build": BUILD / "hermes-SOUL.md",
    },
    "workbuddy": {
        "platform": "claude-code",
        "target": VAULT / ".claude" / "agents" / "workbuddy.md",
        "build": BUILD / "claude-workbuddy.md",
    },
    "xiaochong": {
        "platform": "openclaw",
        "target": Path(os.path.expanduser("~/.openclaw/workspace/AGENTS.md")),
        "build": BUILD / "openclaw-AGENTS.md",
    },
    "claude-md": {
        "platform": "claude-code",
        "target": VAULT / ".claude" / "CLAUDE.md",
        "build": BUILD / "claude-CLAUDE.md",
    },
}

# 手动平台：--apply 跳过整文件覆盖，但 --apply-block 可替换标记段
MANUAL_TARGETS = {"xiaochong", "toubao", "claude-md"}

# 自动平台：--apply 直接覆盖
AUTO_TARGETS = {k for k in TARGETS if k not in MANUAL_TARGETS}

# Deprecated 入口（--verify 检查是否仍被引用）
DEPRECATED = {
    "assistant": {
        "old_target": VAULT / ".claude" / "agents" / "assistant.md",
        "replaced_by": "claudian",
        "reason": "agent_id renamed assistant → claudian (2026-05-26)",
    },
}

# CLAUDE.md 通过 TARGETS["claude-md"] 管理（手动平台，--apply-block 可替换合规块）

# V9 合规块标记
BLOCK_START = "<!-- V9-COMPLIANCE-BLOCK-START -->"
BLOCK_END = "<!-- V9-COMPLIANCE-BLOCK-END -->"
PREFLIGHT_PLACEHOLDER = "<!-- V9-PREFLIGHT-PLACEHOLDER -->"
COMPLIANCE_INJECT = "<!-- V9-COMPLIANCE-INJECT -->"

# 生成头标记（用于检测和剥离）
GENERATED_HEADER_MARKER = "<!-- AUTO-GENERATED by prompt-build.py"


def read_file(path):
    if path.exists():
        return path.read_text(encoding="utf-8")
    return ""


def split_yaml_frontmatter(text):
    """拆分顶层 YAML frontmatter 与正文；没有 frontmatter 则返回原文正文。"""
    if not text.startswith("---\n"):
        return "", text

    match = re.match(r"^---\n(.*?)\n---\n?", text, flags=re.S)
    if not match:
        return "", text

    frontmatter = match.group(1)
    body = text[match.end():]
    return frontmatter, body.lstrip("\n")


def parse_simple_frontmatter(text):
    """解析极简 frontmatter（key: value）；仅用于少量字段读取。"""
    frontmatter, _ = split_yaml_frontmatter(text)
    data = {}
    if not frontmatter:
        return data

    for line in frontmatter.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        data[key.strip()] = value.strip().strip('"').strip("'")
    return data


def has_generated_header(text):
    """检测文本是否以自动生成头开始"""
    return text.startswith(GENERATED_HEADER_MARKER)


def strip_generated_header(text):
    """剥离自动生成头（前 3 行注释 + 1 空行），仅在确实有时剥离"""
    if not has_generated_header(text):
        return text
    lines = text.split("\n")
    # 跳过连续的 <!-- ... --> 注释行和紧随的空行
    i = 0
    while i < len(lines) and lines[i].startswith("<!--"):
        i += 1
    # 跳过紧随的空行
    while i < len(lines) and lines[i].strip() == "":
        i += 1
    return "\n".join(lines[i:])


def content_hash(text):
    """生成内容的短 hash（对剥离 header 后的正文计算）"""
    body = strip_generated_header(text)
    return hashlib.sha256(body.encode("utf-8")).hexdigest()[:8]


def make_header(body, source_desc):
    """生成标准化头部"""
    h = content_hash(body)
    header = f"<!-- AUTO-GENERATED by prompt-build.py @ v{h} -->\n"
    header += f"<!-- 源文件: {source_desc} -->\n"
    header += "<!-- 禁止手改本文件。修改源文件后运行: python3 .prompt-src/prompt-build.py --apply -->\n\n"
    return header


def load_base():
    raw = read_file(SRC / "prompt-base.md")
    _, body = split_yaml_frontmatter(raw)
    return body


def load_delta(agent_id):
    return read_file(AGENTS_DIR / f"{agent_id}.delta.md")


def load_compliance_block():
    """加载 V9 合规块正文（跳过文件头部说明）"""
    raw = read_file(COMPLIANCE_BLOCK_SRC)
    if not raw:
        return ""
    _, raw = split_yaml_frontmatter(raw)
    # 跳过文件顶部的标题和说明（第一个独立 --- 行之后是正文）
    parts = re.split(r"^\-\-\-$", raw, maxsplit=1, flags=re.MULTILINE)
    if len(parts) >= 2:
        return parts[1].strip()
    return raw.strip()


def load_preflight_auto_template():
    """加载自动平台 pre-flight 模板正文（跳过文件头部说明）"""
    raw = read_file(PREFLIGHT_AUTO_SRC)
    if not raw:
        return ""
    _, raw = split_yaml_frontmatter(raw)
    # 跳过文件头（# 标题 + > 说明 + 空行，到第一个 ### 开始）
    match = re.search(r"^### ", raw, flags=re.MULTILINE)
    if match:
        return raw[match.start():].strip()
    return raw.strip()


def render_variables(text, agent_id, agent_meta):
    """替换模板变量"""
    # 路径变量：外部平台用绝对路径，内部平台用相对路径
    if agent_meta["platform"] in ("hermes", "openclaw"):
        status_path = "~/Desktop/obsidianVault/02-项目管理/智能体状态"
        kanban_path = "~/Desktop/obsidianVault/00-MOC/多智能体协作看板.md"
    else:
        status_path = "02-项目管理/智能体状态"
        kanban_path = "00-MOC/多智能体协作看板.md"

    # 从 delta frontmatter / 正文中提取 agent_name
    delta = load_delta(agent_id)
    agent_cn = agent_id  # 默认
    if delta:
        meta = parse_simple_frontmatter(delta)
        agent_cn = meta.get("agent_name", agent_cn)
        if agent_cn == agent_id:
            for line in delta.strip().split("\n"):
                if line.startswith("agent_name:"):
                    agent_cn = line.split(":", 1)[1].strip()
                    break

    text = text.replace("{{STATUS_PATH}}", status_path)
    text = text.replace("{{AGENT_CN}}", agent_cn)
    text = text.replace("{{AGENT_ID}}", agent_id)
    text = text.replace("{{KANBAN_PATH}}", kanban_path)
    return text


def build_compliance_block(agent_id, agent_meta):
    """为自动平台构建完整的合规块（共享规则 + 渲染后的 pre-flight）"""
    compliance = load_compliance_block()
    if not compliance:
        print(f"  [ERROR] v9-compliance-block.md not found or empty")
        return ""

    preflight_template = load_preflight_auto_template()
    if not preflight_template:
        print(f"  [ERROR] preflight-auto-template.md not found or empty")
        return ""

    # 渲染 pre-flight 模板中的变量
    rendered_preflight = render_variables(preflight_template, agent_id, agent_meta)

    # 将渲染后的 pre-flight 注入合规块的 PLACEHOLDER 位置
    if PREFLIGHT_PLACEHOLDER in compliance:
        full_block = compliance.replace(PREFLIGHT_PLACEHOLDER, rendered_preflight)
    else:
        # fallback: 在激活判定铁律前插入
        parts = compliance.split("### 激活判定铁律")
        if len(parts) == 2:
            full_block = parts[0] + rendered_preflight + "\n\n### 激活判定铁律" + parts[1]
        else:
            print(f"  [WARN] compliance block missing '### 激活判定铁律' and PLACEHOLDER")
            full_block = compliance + "\n\n" + rendered_preflight

    return full_block


def render_agent_prompt(base, delta, agent_id, agent_meta):
    """生成自动平台的完整 prompt"""
    # 1. 构建合规块
    compliance_block = build_compliance_block(agent_id, agent_meta)

    # 2. 用合规块替换 base 中的占位符，并包裹 START/END 标记
    wrapped_block = f"{BLOCK_START}\n\n{compliance_block}\n\n{BLOCK_END}"

    if COMPLIANCE_INJECT in base:
        rendered_base = base.replace(COMPLIANCE_INJECT, wrapped_block)
    else:
        # fallback: 如果 base 没有占位符，在第一个 --- 后插入
        print(f"  [WARN] {agent_id}: prompt-base.md missing {COMPLIANCE_INJECT}, injecting after first ---")
        parts = re.split(r"^\-\-\-$", base, maxsplit=1, flags=re.MULTILINE)
        if len(parts) >= 2:
            rendered_base = parts[0] + "---\n\n" + wrapped_block + "\n\n---" + parts[1]
        else:
            rendered_base = wrapped_block + "\n\n" + base

    # 3. 替换 base 中的通用变量（路径 owner 表等可能有变量）
    rendered_base = render_variables(rendered_base, agent_id, agent_meta)

    # 4. 组装最终 prompt
    _, delta_body = split_yaml_frontmatter(delta)
    body = rendered_base + "\n\n---\n\n## Agent 特化配置\n\n" + delta_body
    source_desc = f".prompt-src/prompt-base.md + v9-compliance-block.md + agents/{agent_id}.delta.md"
    header = make_header(body, source_desc)

    return header + body


def extract_block_from_target(content):
    """从目标文件中提取 V9 合规块内容（标记之间的文本）"""
    if BLOCK_START not in content or BLOCK_END not in content:
        return None
    start_idx = content.index(BLOCK_START) + len(BLOCK_START)
    end_idx = content.index(BLOCK_END)
    return content[start_idx:end_idx].strip()


def extract_preflight_from_block(block_content):
    """从合规块中提取 pre-flight 段（灰区兜底之后、激活判定铁律之前）"""
    lines = block_content.split("\n")
    preflight_start = None
    preflight_end = None

    for i, line in enumerate(lines):
        # 找到灰区兜底段结束后的下一个 ### 标题（即 pre-flight 段开始）
        if "### M4/M5" in line and "pre-flight" in line.lower():
            preflight_start = i
        elif "### M3" in line and preflight_start is not None and preflight_end is None:
            # M3 段也是 pre-flight 的一部分，继续
            pass
        elif "### 激活判定铁律" in line:
            preflight_end = i
            break
        elif line.startswith("### 任务完成后") and preflight_start is not None:
            # OpenClaw 有 "### 任务完成后" 段，也是 pre-flight 部分
            pass

    if preflight_start is not None and preflight_end is not None:
        return "\n".join(lines[preflight_start:preflight_end]).strip()
    return None


def extract_shared_from_block(block_content):
    """从合规块中提取共享段（去掉 pre-flight，只留共享规则）"""
    preflight = extract_preflight_from_block(block_content)
    if preflight is None:
        return block_content

    # 用 preflight 分割，得到 before + after
    idx = block_content.find(preflight)
    if idx < 0:
        return block_content
    before = block_content[:idx].rstrip()
    after = block_content[idx + len(preflight):].lstrip()
    return before + "\n\n" + after


def build_expected_block_for_manual(agent_id, agent_meta, current_block):
    """为手动平台构建期望的合规块（共享规则来自真理源 + 保留现有 pre-flight）"""
    compliance = load_compliance_block()
    if not compliance:
        return None

    # 提取当前 pre-flight
    preflight = extract_preflight_from_block(current_block)
    if preflight is None:
        return None

    # 注入 pre-flight 到合规块模板
    if PREFLIGHT_PLACEHOLDER in compliance:
        expected = compliance.replace(PREFLIGHT_PLACEHOLDER, preflight)
    else:
        parts = compliance.split("### 激活判定铁律")
        if len(parts) == 2:
            expected = parts[0] + preflight + "\n\n### 激活判定铁律" + parts[1]
        else:
            return None

    return expected


def apply_block(agent_id, meta):
    """块级替换：只更新手动平台 V9 合规块中的共享规则，保留 pre-flight"""
    target_path = meta["target"]
    current = read_file(target_path)
    if not current:
        print(f"  [ERROR] {agent_id}: target file not found: {target_path}")
        return False

    if BLOCK_START not in current or BLOCK_END not in current:
        print(f"  [ERROR] {agent_id}: V9-COMPLIANCE-BLOCK markers not found in {target_path}")
        return False

    current_block = extract_block_from_target(current)
    if not current_block:
        print(f"  [ERROR] {agent_id}: empty compliance block")
        return False

    # 构建期望块
    expected_block = build_expected_block_for_manual(agent_id, meta, current_block)
    if expected_block is None:
        print(f"  [ERROR] {agent_id}: could not build expected block")
        return False

    # 重建文件
    start_idx = current.index(BLOCK_START)
    end_idx = current.index(BLOCK_END) + len(BLOCK_END)
    before = current[:start_idx]
    after = current[end_idx:]
    new_content = before + BLOCK_START + "\n\n" + expected_block + "\n\n" + BLOCK_END + after

    # 写入
    build_path = meta["build"]
    build_path.parent.mkdir(parents=True, exist_ok=True)
    build_path.write_text(new_content, encoding="utf-8")
    target_path.write_text(new_content, encoding="utf-8")
    print(f"  [APPLIED-BLOCK] {agent_id}: compliance block updated in {target_path}")
    return True


def verify_all():
    """全目标一致性检查：任何 drift → 非零退出"""
    issues = []

    # 1. 检查 deprecated 入口
    for old_id, info in DEPRECATED.items():
        old_path = info["old_target"]
        if old_path.exists():
            content = read_file(old_path)
            if "DEPRECATED" not in content[:200]:
                issues.append(f"[P0] DEPRECATED target {old_id} ({old_path}) exists but not marked deprecated")

    # 2. 检查自动平台：当前文件合规块 vs 从 v9-compliance-block.md 生成的期望块
    base = load_base()
    for agent_id in AUTO_TARGETS:
        meta = TARGETS[agent_id]
        delta = load_delta(agent_id)
        if not delta:
            issues.append(f"[P0] {agent_id}: delta file missing")
            continue

        current = read_file(meta["target"])
        if not current:
            issues.append(f"[P0] {agent_id}: target file missing: {meta['target']}")
            continue

        # 生成期望内容并全文比较正文
        expected = render_agent_prompt(base, delta, agent_id, meta)
        expected_body = strip_generated_header(expected)
        current_body = strip_generated_header(current)

        if expected_body != current_body:
            diff_lines = sum(1 for a, b in zip(
                expected_body.split("\n"), current_body.split("\n")
            ) if a != b)
            diff_lines += abs(len(expected_body.split("\n")) - len(current_body.split("\n")))
            issues.append(f"[P1] {agent_id}: drifted from source ({diff_lines} lines differ)")

        # 额外检查：合规块标记是否存在
        if BLOCK_START not in current:
            issues.append(f"[P0] {agent_id}: V9-COMPLIANCE-BLOCK-START marker missing")
        if BLOCK_END not in current:
            issues.append(f"[P0] {agent_id}: V9-COMPLIANCE-BLOCK-END marker missing")

        # 验证 header hash 一致性
        if has_generated_header(current):
            # 提取当前 hash
            header_match = re.search(r"@ v([a-f0-9]{8})", current.split("\n")[0])
            if header_match:
                current_hash = header_match.group(1)
                expected_hash = content_hash(current)
                if current_hash != expected_hash:
                    issues.append(f"[P2] {agent_id}: header hash stale ({current_hash} != {expected_hash})")

    # 3. 检查手动平台：合规块全文比较
    for agent_id in MANUAL_TARGETS:
        meta = TARGETS[agent_id]
        current = read_file(meta["target"])
        if not current:
            issues.append(f"[P0] {agent_id}: target file missing")
            continue
        if BLOCK_START not in current:
            issues.append(f"[P0] {agent_id}: V9-COMPLIANCE-BLOCK-START marker missing")
            continue
        if BLOCK_END not in current:
            issues.append(f"[P0] {agent_id}: V9-COMPLIANCE-BLOCK-END marker missing")
            continue

        current_block = extract_block_from_target(current)

        # 构建期望块并全文比较
        expected_block = build_expected_block_for_manual(agent_id, meta, current_block)
        if expected_block is None:
            issues.append(f"[P1] {agent_id}: could not build expected block for comparison")
            continue

        # 规范化比较（去掉首尾空白和多余空行）
        def normalize(s):
            return re.sub(r"\n{3,}", "\n\n", s.strip())

        if normalize(current_block) != normalize(expected_block):
            # 计算差异
            current_lines = normalize(current_block).split("\n")
            expected_lines = normalize(expected_block).split("\n")
            diff_count = sum(1 for a, b in zip(current_lines, expected_lines) if a != b)
            diff_count += abs(len(current_lines) - len(expected_lines))
            issues.append(f"[P1] {agent_id}: compliance block drift ({diff_count} lines differ)")

    # 4. 报告
    if not issues:
        print("\n  [OK] All targets verified. No drift detected.")
        return 0
    else:
        print(f"\n  [DRIFT] {len(issues)} issue(s) found:")
        for issue in sorted(issues):
            print(f"    {issue}")
        return 1  # 任何 drift 都非零退出


def diff_files(old_content, new_content, filename):
    """生成 unified diff"""
    old_lines = old_content.splitlines(keepends=True)
    new_lines = new_content.splitlines(keepends=True)
    diff = difflib.unified_diff(
        old_lines, new_lines,
        fromfile=f"current/{filename}",
        tofile=f"generated/{filename}",
        lineterm=""
    )
    return "".join(diff)


def main():
    apply_mode = "--apply" in sys.argv
    apply_block_mode = "--apply-block" in sys.argv
    verify_mode = "--verify" in sys.argv
    diff_only = "--diff" in sys.argv

    # --verify 模式：独立运行
    if verify_mode:
        print("=" * 60)
        print("prompt-build.py --verify")
        print("=" * 60)
        exit_code = verify_all()
        sys.exit(exit_code)

    # --apply-block 模式：只处理手动平台
    if apply_block_mode:
        print("=" * 60)
        print("prompt-build.py --apply-block")
        print("=" * 60)
        success = 0
        for agent_id in MANUAL_TARGETS:
            if apply_block(agent_id, TARGETS[agent_id]):
                success += 1
        print(f"\n  Result: {success}/{len(MANUAL_TARGETS)} targets updated")
        sys.exit(0 if success == len(MANUAL_TARGETS) else 1)

    # 默认模式 / --apply / --diff
    if not diff_only:
        BUILD.mkdir(parents=True, exist_ok=True)

    base = load_base()
    diffs = []
    stats = {"unchanged": 0, "changed": 0, "new": 0}

    # 生成各 agent prompt
    for agent_id, meta in TARGETS.items():
        # 手动平台跳过整文件生成（用 --apply-block）
        if agent_id in MANUAL_TARGETS:
            if apply_mode:
                print(f"  [SKIP-APPLY] {agent_id} (手动平台，请用 --apply-block)")
            continue

        delta = load_delta(agent_id)
        if not delta:
            print(f"  [SKIP] {agent_id}: no delta file")
            continue

        content = render_agent_prompt(base, delta, agent_id, meta)
        current = read_file(meta["target"])

        # 比较正文（剥离 header）
        current_body = strip_generated_header(current) if current else ""
        new_body = strip_generated_header(content)

        if current_body == new_body:
            stats["unchanged"] += 1
        elif current:
            stats["changed"] += 1
            diffs.append((
                f"{agent_id} ({meta['platform']})",
                diff_files(current, content, str(meta["target"].name))
            ))
        else:
            stats["new"] += 1

        if not diff_only:
            meta["build"].parent.mkdir(parents=True, exist_ok=True)
            meta["build"].write_text(content, encoding="utf-8")
        if apply_mode:
            meta["target"].parent.mkdir(parents=True, exist_ok=True)
            meta["target"].write_text(content, encoding="utf-8")
            print(f"  [APPLIED] {agent_id} -> {meta['target']}")

    # 检查 deprecated
    for old_id, info in DEPRECATED.items():
        old_path = info["old_target"]
        if old_path.exists():
            content = read_file(old_path)
            if "DEPRECATED" not in content[:200]:
                print(f"  [WARN] Deprecated target {old_id} ({old_path}) not marked")

    # 报告
    print(f"\n{'='*60}")
    print(f"prompt-build.py 报告")
    print(f"{'='*60}")
    print(f"  真理源:")
    print(f"    合规块: .prompt-src/v9-compliance-block.md")
    print(f"    Pre-flight: .prompt-src/preflight-auto-template.md")
    print(f"    基类: .prompt-src/prompt-base.md")
    print(f"  Auto targets: {len(AUTO_TARGETS)} ({', '.join(sorted(AUTO_TARGETS))})")
    print(f"  Manual targets: {len(MANUAL_TARGETS)} ({', '.join(sorted(MANUAL_TARGETS))})")
    print(f"  Deprecated: {len(DEPRECATED)} ({', '.join(DEPRECATED.keys())})")
    print(f"  结果: {stats['unchanged']} 不变 / {stats['changed']} 有变更 / {stats['new']} 新文件")
    print(f"  模式: {'--apply (已覆盖自动目标)' if apply_mode else '--diff (仅预览)' if diff_only else '生成到 _build/'}")

    if diffs:
        print(f"\n{'='*60}")
        print("变更详情：")
        print(f"{'='*60}")
        for name, d in diffs:
            print(f"\n--- {name} ---")
            lines = d.split("\n")
            for line in lines[:40]:
                print(line)
            if len(lines) > 40:
                print(f"  ... ({len(lines) - 40} more lines)")

    if not apply_mode and not diff_only:
        print(f"\n生成文件在: {BUILD}/")
        print("确认无误后执行:")
        print("  python3 .prompt-src/prompt-build.py --apply        # 覆盖自动平台")
        print("  python3 .prompt-src/prompt-build.py --apply-block  # 替换手动平台合规块")
        print("  python3 .prompt-src/prompt-build.py --verify       # 全目标一致性检查")


if __name__ == "__main__":
    main()
